version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'

  todo-service:
    build: ./todo-service
    ports:
      - '5000:5000'
    depends_on:
      - mongo

  api-gateway:
    build: ./api-gateway
    ports:
      - '8080:8080'
    depends_on:
      - todo-service

  auth-service:
    build: ./auth-service
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/auth-db
      - JWT_SECRET=supersecretkey
    depends_on:
      - mongo
