version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'

  todo-service:
    build: ./todo-service
    ports:
      - '5000:5000'
    depends_on:
      - mongo

  api-gateway:
    build: ./api-gateway
    ports:
      - '8080:8080'
    depends_on:
      - todo-service

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api-gateway
