apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: sangs29/auth-service:latest
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-secret
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - port: 5001
      targetPort: 5001
  type: ClusterIP
